version: "3"

networks:
  frontend:
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - frontend
  loadbalancer:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    links:
      - app
    networks:
      - frontend